// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/jwks.json": {
            "get": {
                "description": "Public keys for verifying RS256-signed access tokens (RFC 7517).",
                "produces": [
                    "application/jwk-set+json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "JWKS endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/.well-known/oauth-authorization-server": {
            "get": {
                "description": "Returns the OAuth 2.0 Authorization Server Metadata document",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "RFC 8414 metadata document",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.AuthorizationServerMetadata"
                        }
                    }
                }
            }
        },
        "/.well-known/openid-configuration": {
            "get": {
                "description": "Returns the OIDC discovery document",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "OIDC Discovery 1.0 metadata document",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.AuthorizationServerMetadata"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/authorize": {
            "get": {
                "description": "Starts an OAuth 2.1 + OIDC authorize flow (ADR-0011)",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Authorization endpoint",
                "responses": {
                    "302": {
                        "description": "Redirect to login-ui sign-in page"
                    }
                }
            }
        },
        "/oauth/introspect": {
            "post": {
                "description": "Validates and returns metadata for a token per RFC 7662",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Introspect token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token to introspect",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.IntrospectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/revoke": {
            "post": {
                "description": "Revokes a token per RFC 7009",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Revoke token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token to revoke",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token revoked"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "description": "Issues an OAuth2 access token using the specified grant type (RFC 6749)",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Issue access token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth2 grant type",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "client_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client secret",
                        "name": "client_secret",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited list of scopes",
                        "name": "scope",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code verifier",
                        "name": "code_verifier",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI",
                        "name": "redirect_uri",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.GrantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/userinfo": {
            "get": {
                "description": "Returns the OIDC claims permitted by the access token's scopes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oidc"
                ],
                "summary": "OIDC UserInfo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputil.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.AuthorizationServerMetadata": {
            "type": "object",
            "properties": {
                "authorization_details_types_supported": {
                    "description": "AuthorizationDetailsTypesSupported lists the RFC 9396 §10 type\ndiscriminators this server understands (ADR-0017). Emitted on\nboth /.well-known endpoints because clients use it to decide\nwhether to opt into the richer parameter.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorization_endpoint": {
                    "type": "string"
                },
                "claim_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "claims_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code_challenge_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_session_endpoint": {
                    "type": "string"
                },
                "grant_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "introspection_endpoint": {
                    "type": "string"
                },
                "introspection_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "type": "string"
                },
                "jwks_uri": {
                    "type": "string"
                },
                "registration_endpoint": {
                    "type": "string"
                },
                "request_parameter_supported": {
                    "description": "RequestParameterSupported and friends are pointer-bool so the\n\"false\" value is distinguishable from \"omitted\" — RFC 8414 §2 lets\nus emit either, and emitting an explicit false is what every major\nIdP does to telegraph that the feature is intentionally off.",
                    "type": "boolean"
                },
                "request_uri_parameter_supported": {
                    "type": "boolean"
                },
                "require_request_uri_registration": {
                    "type": "boolean"
                },
                "response_modes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "response_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "revocation_endpoint": {
                    "type": "string"
                },
                "revocation_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "service_documentation": {
                    "type": "string"
                },
                "subject_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_endpoint": {
                    "type": "string"
                },
                "token_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ui_locales_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userinfo_endpoint": {
                    "description": "OIDC Discovery 1.0 §3 additions. Emitted in the OIDC Discovery\ndocument; RFC 8414 §2 tolerates the extras but they convey OIDC\nsemantics, so the RFC 8414 path omits them.",
                    "type": "string"
                }
            }
        },
        "github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.GrantResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "id_token": {
                    "description": "IDToken is the OIDC ID token (OIDC Core §2) issued when the granted\nscopes include \"openid\". Empty + omitempty when OIDC mode is not active,\nmatching the OAuth-only response shape clients see today.",
                    "type": "string"
                },
                "issued_token_type": {
                    "description": "IssuedTokenType is the RFC 8693 §2.2.1 echo of the issued token\ntype URN. Omitted from non-token-exchange responses so the wire\nshape for client_credentials / authorization_code / refresh_token\nis unchanged — RFC 8693 requires the field only on the\ntoken-exchange response.",
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "github_com_ocrosby_identity-platform-go_services_auth-server_internal_domain.IntrospectResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "aud": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorization_details": {
                    "description": "AuthorizationDetails echoes the RFC 9396 §10.1 granted-details\narray. Omitted when empty so RAR-unaware resource servers see\nthe same shape they always have.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "client_id": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer"
                },
                "iat": {
                    "type": "integer"
                },
                "iss": {
                    "type": "string"
                },
                "jti": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "sub": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "httputil.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Auth Server API",
	Description:      "OAuth2 Authorization Server - token issuance, introspection, and revocation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
