// Package application contains the business logic for identity-service.
// EmailVerificationService implements the two-step verification flow:
//
//  1. RequestVerification — generate a single-use token, persist its SHA-256
//     hash with an expiry, send the plaintext token to the user's email.
//  2. VerifyEmail         — accept the plaintext token, look up the hash,
//     verify validity, mark the user's email as verified, mark the token used.
//
// Security properties enforced here:
//   - Tokens are generated by crypto/rand and printed as URL-safe base64.
//   - Only the SHA-256 hash of the token is stored; a database leak does not
//     expose live tokens.
//   - RequestVerification responds the same way for known and unknown
//     emails so the endpoint cannot be used to enumerate users.
//   - Tokens are single-use: a non-nil UsedAt means redemption is rejected.
//   - Tokens are time-bounded by EmailVerificationConfig.TokenTTL.
package application

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jedi-knights/go-platform/apperrors"

	"github.com/ocrosby/identity-platform-go/services/identity-service/internal/domain"
)

// EmailVerificationConfig holds tunables for the verification flow. Defaults
// are applied when fields are zero so callers can construct an empty struct
// and still get sensible behavior.
type EmailVerificationConfig struct {
	// TokenTTL is how long a freshly issued verification token remains
	// redeemable. Defaults to 24 hours when zero.
	TokenTTL time.Duration

	// VerificationURLTemplate is interpolated with the plaintext token and
	// handed to the EmailSender. Use "{{token}}" as the placeholder. The
	// template stays out of identity-service's own configuration so this
	// service does not need to know its caller's domain.
	//
	// Example: "https://app.example.com/verify-email?token={{token}}"
	VerificationURLTemplate string

	// TokenByteLength is the size of the random token in bytes (the
	// plaintext value is base64-url-encoded so the printed length is
	// ceil(N * 4/3)). Defaults to 32 (256 bits → 43-char base64 string).
	TokenByteLength int
}

// EmailVerificationService implements ports.EmailVerifier.
type EmailVerificationService struct {
	users  domain.UserRepository
	tokens domain.VerificationTokenRepository
	sender domain.EmailSender
	cfg    EmailVerificationConfig
	now    func() time.Time // injected for tests
}

// NewEmailVerificationService wires the verification flow. The `now` argument
// may be nil; the production path uses time.Now.
func NewEmailVerificationService(
	users domain.UserRepository,
	tokens domain.VerificationTokenRepository,
	sender domain.EmailSender,
	cfg EmailVerificationConfig,
) *EmailVerificationService {
	cfg = applyDefaults(cfg)
	return &EmailVerificationService{
		users:  users,
		tokens: tokens,
		sender: sender,
		cfg:    cfg,
		now:    time.Now,
	}
}

// RequestVerification issues a token for the user matching req.Email and
// hands it to the EmailSender as a verification URL.
//
// The response shape carries no information about whether req.Email is on
// file or whether the email was already verified — that prevents drive-by
// enumeration attacks. Errors are returned only when they cannot leak user
// existence (e.g. infrastructure failures).
func (s *EmailVerificationService) RequestVerification(
	ctx context.Context,
	req domain.RequestVerificationRequest,
) error {
	if strings.TrimSpace(req.Email) == "" {
		return apperrors.New(apperrors.ErrCodeBadRequest, "email is required")
	}

	user, skip, err := s.findVerifiableUser(ctx, req.Email)
	if err != nil {
		return err
	}
	if skip {
		return nil
	}

	plaintext, err := s.issueToken(ctx, user.ID)
	if err != nil {
		return err
	}

	return s.dispatchVerificationEmail(ctx, user, plaintext)
}

// findVerifiableUser looks up the user for an email and reports whether the
// caller should silently no-op (unknown email or already verified). Both of
// those branches must respond identically to the success path to avoid leaking
// account existence — they are the same as far as the caller is concerned.
func (s *EmailVerificationService) findVerifiableUser(
	ctx context.Context,
	email string,
) (user *domain.User, skip bool, err error) {
	user, err = s.users.FindByEmail(ctx, email)
	if err != nil {
		if apperrors.IsNotFound(err) {
			return nil, true, nil
		}
		return nil, false, fmt.Errorf("looking up user: %w", err)
	}
	if user.IsEmailVerified() {
		return nil, true, nil
	}
	return user, false, nil
}

// issueToken generates a fresh single-use token and persists its hash.
func (s *EmailVerificationService) issueToken(ctx context.Context, userID string) (plaintext string, err error) {
	plaintext, hash, err := newToken(s.cfg.TokenByteLength)
	if err != nil {
		return "", fmt.Errorf("generating token: %w", err)
	}
	now := s.now()
	record := &domain.VerificationToken{
		TokenHash: hash,
		UserID:    userID,
		ExpiresAt: now.Add(s.cfg.TokenTTL),
		CreatedAt: now,
	}
	if err := s.tokens.Save(ctx, record); err != nil {
		return "", fmt.Errorf("saving verification token: %w", err)
	}
	return plaintext, nil
}

// dispatchVerificationEmail renders the verification URL and hands it to the
// EmailSender adapter.
func (s *EmailVerificationService) dispatchVerificationEmail(
	ctx context.Context,
	user *domain.User,
	plaintext string,
) error {
	url, err := renderVerificationURL(s.cfg.VerificationURLTemplate, plaintext)
	if err != nil {
		return fmt.Errorf("rendering verification URL: %w", err)
	}
	if err := s.sender.SendVerificationEmail(ctx, domain.VerificationEmail{
		To:              user.Email,
		Name:            user.Name,
		VerificationURL: url,
	}); err != nil {
		return fmt.Errorf("sending verification email: %w", err)
	}
	return nil
}

// VerifyEmail redeems a plaintext token and marks the user verified. The
// token is hashed before lookup so the database never holds plaintext.
//
// All "this token is no good" cases (unknown, expired, already used) collapse
// to a single ErrCodeUnauthorized so callers cannot probe token validity.
func (s *EmailVerificationService) VerifyEmail(
	ctx context.Context,
	req domain.VerifyEmailRequest,
) (*domain.VerifyEmailResponse, error) {
	token := strings.TrimSpace(req.Token)
	if token == "" {
		return nil, apperrors.New(apperrors.ErrCodeBadRequest, "token is required")
	}

	hash := hashToken(token)
	now := s.now()

	record, err := s.findRedeemableToken(ctx, hash, now)
	if err != nil {
		return nil, err
	}

	return s.completeRedemption(ctx, record, hash, now)
}

// findRedeemableToken loads a token by hash and validates it is still
// redeemable. Unknown / expired / already-used tokens all collapse to
// ErrCodeUnauthorized so callers cannot probe token validity.
func (s *EmailVerificationService) findRedeemableToken(
	ctx context.Context,
	hash string,
	now time.Time,
) (*domain.VerificationToken, error) {
	record, err := s.tokens.FindByHash(ctx, hash)
	if err != nil {
		if apperrors.IsNotFound(err) {
			return nil, apperrors.New(apperrors.ErrCodeUnauthorized, "invalid or expired token")
		}
		return nil, fmt.Errorf("looking up token: %w", err)
	}
	if !record.ExpiresAt.After(now) || record.UsedAt != nil {
		return nil, apperrors.New(apperrors.ErrCodeUnauthorized, "invalid or expired token")
	}
	return record, nil
}

// completeRedemption marks the user verified, burns the token, and returns
// the response payload assembled from the freshly-loaded user record.
func (s *EmailVerificationService) completeRedemption(
	ctx context.Context,
	record *domain.VerificationToken,
	hash string,
	now time.Time,
) (*domain.VerifyEmailResponse, error) {
	if err := s.users.MarkEmailVerified(ctx, record.UserID, now); err != nil {
		return nil, fmt.Errorf("marking email verified: %w", err)
	}
	if err := s.tokens.MarkUsed(ctx, hash, now); err != nil {
		return nil, fmt.Errorf("marking token used: %w", err)
	}
	user, err := s.users.FindByID(ctx, record.UserID)
	if err != nil {
		return nil, fmt.Errorf("loading user after verification: %w", err)
	}
	return &domain.VerifyEmailResponse{
		UserID:     user.ID,
		Email:      user.Email,
		VerifiedAt: now,
	}, nil
}

// applyDefaults fills in sensible defaults for zero-value fields.
func applyDefaults(cfg EmailVerificationConfig) EmailVerificationConfig {
	if cfg.TokenTTL == 0 {
		cfg.TokenTTL = 24 * time.Hour
	}
	if cfg.TokenByteLength == 0 {
		cfg.TokenByteLength = 32
	}
	return cfg
}

// newToken returns (plaintext, sha256-hex). The plaintext is URL-safe base64
// without padding so it can drop straight into a query string.
func newToken(byteLen int) (plaintext, hash string, err error) {
	if byteLen <= 0 {
		return "", "", errors.New("byteLen must be positive")
	}
	buf := make([]byte, byteLen)
	if _, err := rand.Read(buf); err != nil {
		return "", "", fmt.Errorf("reading random bytes: %w", err)
	}
	plaintext = base64.RawURLEncoding.EncodeToString(buf)
	return plaintext, hashToken(plaintext), nil
}

// hashToken returns the SHA-256 hex digest of the plaintext token. We use a
// plain hash (not a per-row salt + bcrypt) because the plaintext is
// cryptographically random and high-entropy — a fast hash is sufficient.
func hashToken(plaintext string) string {
	sum := sha256.Sum256([]byte(plaintext))
	return hex.EncodeToString(sum[:])
}

// renderVerificationURL substitutes {{token}} in the template. If the
// template is empty we return the token alone so the EmailSender can decide
// how to format the URL (useful for the stdout sender in tests).
func renderVerificationURL(template, token string) (string, error) {
	if template == "" {
		return token, nil
	}
	if !strings.Contains(template, "{{token}}") {
		return "", fmt.Errorf("template missing {{token}} placeholder")
	}
	return strings.ReplaceAll(template, "{{token}}", token), nil
}
